/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppItem } from './types';

export const INITIAL_APPS: AppItem[] = [
  // FEATURED APPS (On the Home Page Grid)
  {
    id: 'chavis-creative',
    title: 'Chavis Creative',
    developer: 'Chavis Dev Studio',
    rating: 4.8,
    size: '18 MB',
    category: 'Tools',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQ65eIpPg8e-upYCQExCYdX18KcF5S_WF9kOyRO_DbZEqCTRpIUryUk3cQW-oZMHR8z3E8GuQBPo4nw7HuvcRSaAgt-iadbHzSC2t5FeD4x37edvZxIJmLDLRUwi81Tqm-m9W5PxEz4FNB6FmtBc-t8sP4Fen6acbC4u7YQS_4uzMhvPBov3XZPj2U8uz7YDuPRiYFJ_6rjFhCgB8zuIamq4m8rjPCpbGQ1uH1tNsL9AlQf5jYh_eygH1DuJp8R4aDO6zWJ4YDsPY',
    description: 'A vibrant, modern premium graphic design and vector illustration suite for mobile creators, optimized for speed and precise touch interaction.',
    downloadsCount: 1450,
    isFeatured: true,
    dateAdded: '2026-05-15',
  },
  {
    id: 'task-master-pro',
    title: 'Task Master Pro',
    developer: 'Chavis Productivity',
    rating: 4.9,
    size: '14 MB',
    category: 'Productivity',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCEpfheUELIVq0axjNVDx7L8wfPpOvZs3CQEtQtQ3A8O14VQ0zyG5BgesIf6mAePWczRTyJorHraGhp2rnxsgeQs9FTORX_KFx7Bg4ikpKPawNbEpUfo7wWtCBhuEm6D9xa-FSfCEa8FNZvHMPMYg2p8tQHz4CiU5FSsyzkdOCRlz3NwyWqID-uHoXVadjFdFhaOFRHSPsFgV7DRXMEIdRSN7UuuyN_Lo2i4DGofl-uBEMppJBuZTgxSVuTTkKCkkS_UWtNB2SLeJc',
    description: 'An elegant task management suite showcasing a minimalist checkbox with native widget widgets, focus timers, and intelligent statistics analysis.',
    downloadsCount: 2310,
    isFeatured: true,
    dateAdded: '2026-05-10',
  },
  {
    id: 'nitro-racer-z',
    title: 'Nitro Racer Z',
    developer: 'Arcade Games Ltd',
    rating: 4.5,
    size: '128 MB',
    category: 'Games',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeVOs4Z9OYlb1irFbdNHjmyZ8oWbOTIU6XFmUS_ormEGCHMnS0IhqMGKFtI0UIELtKNL-vzjgfJvcuHpF8xlKjPMyO3WiqJCJbZzXQttqH6hMelwNail-3PtSG6ebLZbSgRcoDGiNfXqmu9dHjDjcbJ7AjAOwqsfkOi5RaxOByxVGJs2e2_d5mjcU2OOHNPJZCRkYn3vNkXQjm_jntu1Ha-nTploAWyJALkGaollqyAXHxpVsc3p4m9bouor0A6h1bPbzIZXboAbk',
    description: 'Sleek sports car arcade racing featuring stylized abstract vehicle models, modern lighting, and responsive drift physics perfect for mobile controls.',
    downloadsCount: 5200,
    isFeatured: true,
    dateAdded: '2026-04-20',
  },
  {
    id: 'cloud-sync',
    title: 'Cloud Sync',
    developer: 'Chavis Infrastructure',
    rating: 4.7,
    size: '8 MB',
    category: 'Tools',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAL72AHMr6yfLVCl6VYxCkug9aMl44Hy6mFcqT67JRSOEYhT_qKtbuFKpUjutg-EnnUSMgjRkl5WD-9gyZSW5hvE7rr4Hp-IWQ01XTJQsTFcdXyjKhkQvQvb6absW6iFqk_tJ1m6fUSw2MpoBrCYqP4EmgyhAIRBDYo9bPq7Xp63uU77-aiZDgGigCv8gpwUmHCw0t-4cgLUzehH5827lYxqqXY7nw-mJ-XuNg0UdMI40sqaG-VgfRYiHITq2Qy7aKTfDNkUGIqGVw',
    description: 'Sophisticated cloud locker and sync manager that guarantees real-time end-to-end encryption for photos, documents, and system backups.',
    downloadsCount: 890,
    isFeatured: true,
    dateAdded: '2026-05-22',
  },

  // CATALOG UNIQUE APPS
  {
    id: 'focuspro-tools',
    title: 'FocusPro Tools',
    developer: 'Chavis Dev Studio',
    rating: 4.8,
    size: '12 MB',
    category: 'Productivity',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3KrO9sKKEarXp7ODLwGcS_LY_9649COE3tgSVrgqNRZYuHiqCN-eRX83H9Q8CbK2q1m3tyAWzD4QnT3HMDIXUt4Bj_ufxC2qXdFkSFloil68ZmHH-dNK13ay3hbizOWHIsNyht1zaAis_iN45t1UwSvYDfeqFUVRsBbdAf3Q8OuwrM96q1BD1CZbmwrArAtbHz5dlKl3-1vrJI2gqhyL6X8eFDLzmNxVAcIF98syNcYkS_-l1UcmuGBhFxSSswILpP_n78tgVwbU',
    description: 'The ultimate productivity companion designed for the modern Android ecosystem. Combines block lists, site controls, and focus states.',
    downloadsCount: 3120,
    dateAdded: '2026-03-01',
  },
  {
    id: 'neon-velocity',
    title: 'Neon Velocity',
    developer: 'Arcade Games Ltd',
    rating: 4.5,
    size: '145 MB',
    category: 'Games',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RVP7ZgYweOzFoWdLdth3suSYTHuFegAAmEQhO2KpJLAgJHUIjCzrjo4vmZ12_mUjUSwT9nN6m9P2Z36h_I7urEaMtkur9xjFFNgGfQNc0qZiYd9W3_Bn7seYPxtZHCiLpVn_2GtjYx1r9RnUHUnNTfK8NT6TkYwnbTAsniGpvqZxruvNJzwtnEItj5ZatlI5UxyQ-tdEWxTlZOuf6c6NHFIB_TtzZSgCFq9X0id5gyOibAtSiHCwN6BKzzfwoYJiOzn9v6ApvLM',
    description: 'High-speed synthetic neon racing style action with stunning dynamic layouts, high fidelity physics modeling, and multiplayer leaderboards.',
    downloadsCount: 1980,
    dateAdded: '2026-03-15',
  },
  {
    id: 'eduplus-academy',
    title: 'EduPlus Academy',
    developer: 'Global Learning Hub',
    rating: 4.9,
    size: '42 MB',
    category: 'Education',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6UDQ_v7BL-2mLfn-4vrIJjbE14MPQq-uqv7X-goJSsOM7HC5KSmJW0l2x6_KtnRNZmS02LdkbqpXGL2FvsD24lbQmgpKHwYd4wGASYHW892YxhYn1eGnn9PD8rWt5ifVWVEdFDsus17WDqXkY2w1tr9JGuTdseatheLeUdmNkZ-HAkgqHYegwZ759Bx5V2nf9EkJ8NJhlp91wHhTdlklFnL-TjaDaiou8b3y4wXxkwf1CklHG1jLiQRBItow6CEruzj9r8l9bT3U',
    description: 'An advanced, highly intuitive educational space with specialized tutorials, coding playgrounds, math solvers, and native achievement charts.',
    downloadsCount: 4500,
    dateAdded: '2026-02-28',
  },
  {
    id: 'circle-social',
    title: 'Circle Social',
    developer: 'NexGen Social',
    rating: 4.2,
    size: '28 MB',
    category: 'Social',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAszKaPYqr-JwbWcpg-UpgcPSUSmHciTqkDZWFtkSRZprsSSQj-yoarH9ntQXUk6tS5Tjz6RRACbYAFK9g_yEMKXDLU-fsTKl-omrC2UkXTckfuN6d3CVMUQTbD9xVu7OZkV8ciwA8TLa1rTd4UC66DE6-cfTTvM9BawJ41InfKlFXNBcXSuSPgn8FKXJz9JHJixrutAGGFgbkehjlPrelpQT8HWVmvem1DxHK9d740WsBYmq8afHVNAitkjISAabcumFUtkt9mb0s',
    description: 'Connect with like-minded creators and build local groups in a clean, privacy-focused modern environment with integrated audio chats.',
    downloadsCount: 880,
    dateAdded: '2026-03-20',
  },
  {
    id: 'smart-ledger',
    title: 'Smart Ledger',
    developer: 'Chavis Fintech',
    rating: 4.7,
    size: '15 MB',
    category: 'Productivity',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuANXCk8MGX7dRGrpTqq_EJDwT0aRhomLLit0Hvv4ZzbLJMgGb1zN-PxFQTYfY35AZ5qf0K92WMOAtyq_EAs1YR6y2UFoCnszaY4iv483WDqqC-MbCFUQaHXuEg4nHeUtSEdw2Xweem6MU5mkm-kaIzwf71eVBR9GzwA2xjOyhm0F0woxJLDI0XcZjnq_uHNf27GU951DxnjlC1P855ZqAkd99Vn_c7nfbEoSX4ndwZ1x-4Dw1FmFA6N7mG7FQrcM5i-JcBB8pJumKw',
    description: 'Personalized wealth and expense control app designed around structural modern tables, visual progress charts, and exportable PDFs.',
    downloadsCount: 1670,
    dateAdded: '2026-04-05',
  },
  {
    id: 'dev-studio-mobile',
    title: 'Dev Studio Mobile',
    developer: 'OpenSource Masters',
    rating: 4.6,
    size: '58 MB',
    category: 'Tools',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArhEY_WzvTpszG3_AV0hjOrO7e7WorXKPgcxhyb_XZ69dS5ZPzRkSy7CBCHKotlRT4yEbpriGLlNmj0RogNVdWFb_ugegtF5SPqmTcEyakcY0iGnNoEkTBnb24lIZfEfodYKSRLKaK4GsxM4gizt82OgnJeWAm7QVoRAQ9dGMnYpDyzrgFuS9tQYFrvJ5bryZ2DO7qyPCKJjf9_0MHvRoyVVFPpWGqhGv-fkAUHQH59UZKfKHJWoCRI1OZNkSPppYspaldi0o9R9o',
    description: 'High-speed code drafting with advanced highlighting for 30+ languages, smart indentation, and robust native FTP/Docker connections.',
    downloadsCount: 2200,
    dateAdded: '2026-03-30',
  },

  // RECENT RELEASES (Horizontal Row)
  {
    id: 'cam-pro-plus',
    title: 'Cam Pro Plus',
    developer: 'Fotografía',
    rating: 4.9,
    size: '24 MB',
    category: 'Tools',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBJCVN4ieVoTRiCaYlzZpgPVsv7fYtyU03CLvEZdz-h801Faa-4UZ7zkA1CUIVLVyVwfQ3WNElgaBo-ZDlcNk-obOBsbcWKiexq5Uz949aLnZJAgbJY2KPw_yNu_gszOQKsuHsuT0O1vuNF6WPUqCOGbQkIBwrw4OYj0UWf9ijYftsi64Rg6GNNncndZqZA_nCftk12KDZI1FD5pjdtdBC7CtcGqhTUXIBngcmS_jgAIt294P8ooMZIIUyR28D2C1gv7hOk9QxzMlA',
    description: 'A dynamic, high-definition camera overlay with manual shutters, DSLR exposures, and clean RAW-format recording capabilities.',
    downloadsCount: 1540,
    isRecent: true,
    dateAdded: '2026-06-01',
  },
  {
    id: 'zen-mind',
    title: 'Zen Mind',
    developer: 'Bienestar',
    rating: 4.6,
    size: '32 MB',
    category: 'Entertainment',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBpaZId30UaaCx5t-2_9Q9ywXkQ0I5PBngBa4lG7dqiLG9JYRulde0PeSAalbEpue699vBX3vWqNuWRDsMzLNtioWpjIkCo8Zvm7bGiePNOpVlMQDi1JRwiCv47RXwTHkoVdCm2uQe_IHSh5G7SLPS6KIZb7oyV40SmZJYM18_2fsBq7cQ7w0zFX-uDxmyx4mWHzAGGeGPB7l0gtItaujT30fC1gC4EENYKKx5Q6D4gMy3rFBEIIwjCpOg2qNlc1OV1FzwuHe5uVyQ',
    description: 'Ethereal guided audios, clean visual respiration feedback loops, and calming custom soundtracks meant to elevate focus and restore alignment.',
    downloadsCount: 970,
    isRecent: true,
    dateAdded: '2026-05-28',
  },
  {
    id: 'wallet-safe',
    title: 'Wallet Safe',
    developer: 'Finanzas',
    rating: 4.8,
    size: '19 MB',
    category: 'Productivity',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2CYorD4JF6A0lAaWtPyq5him-C4ZyNZpIQaVtdwHZJk9Imz3e949Z1bezD1JMXsjHu8euTGmJ0BRWR_uC9B04BHjlnVnYmim945NusDjGWdxFf_ZVMkCOhbopOjhNuqzshd2tWEBiNhusfg276S22PWLFwA4isoD-5A8-q2E2gSJ33CbQggp_zTmPInswFdQlEF-OOyDjF2rAgecDQQ49Nb1PYssalQfG4uG8HrARgKCIEXAgU4L7m30_UBiyXk9OOeQhYTdMuRc',
    description: 'Local vault backup that stores bank parameters, offline cryptokeys, and regular transactional lists safely using biometric access locks.',
    downloadsCount: 1430,
    isRecent: true,
    dateAdded: '2026-05-30',
  },
  {
    id: 'code-lite',
    title: 'Code Lite',
    developer: 'Desarrollo',
    rating: 4.4,
    size: '15 MB',
    category: 'Tools',
    iconUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEN1oqD35Bi5cUngXlvEyFT4ksbtLk2NNzY7maK2r8UAjS-JBskKI9GmU3-cjqsfOfcnYbu85Ph3qQAe61RHih0HtUFmpHPPWgl_P2uoiXWEdjuXPXnXo5gX9NhqoKUmNMXnDYuucLsZVBtI975F02bMA1QUlg2owx84DTiCbVniIkAdPyPr2FVgXIqUZHLUyeS9GhFZvUb6FgBJaaaY_5Qdps266e8FkRAPG4i8EPExHpZUxKtGRgKeYNLVAiftWcraLmJ9BKEx4',
    description: 'Systematic, ultra-light code editor carrying custom indentation guides, theme parameters, and a direct local compiler engine.',
    downloadsCount: 1100,
    isRecent: true,
    dateAdded: '2026-05-29',
  }
];

export const CATEGORIES = [
  { id: 'all', name: 'Todos', icon: 'apps' },
  { id: 'Tools', name: 'Herramientas', icon: 'build' },
  { id: 'Games', name: 'Juegos', icon: 'sports_esports' },
  { id: 'Education', name: 'Educación', icon: 'school' },
  { id: 'Productivity', name: 'Productividad', icon: 'task_alt' },
  { id: 'Social', name: 'Social', icon: 'groups' },
  { id: 'Entertainment', name: 'Entretenimiento', icon: 'theater_comedy' }
];

export const SORT_OPTIONS = [
  { value: 'popular', label: 'Más populares' },
  { value: 'rating', label: 'Mejor calificados' },
  { value: 'newest', label: 'Más recientes' },
  { value: 'alphabetical', label: 'Orden alfabético' }
];
